const clases = [
  { name: 'JavaScript Drum Kit', id: '01' },
  { name: 'CSS + JS Clock', id: '02' },
  { name: 'Playing with CSS Variables and JS', id: '03' },
  { name: 'Array Cardio Day 1', id: '04' },
  { name: 'Flex Panels Image Gallery', id: '05' },
  { name: 'Ajax Type Ahead', id: '06' },
  { name: 'Array Cardio Day 2', id: '07' },
  { name: 'Fun with HTML5 Canvas', id: '08' },
  { name: '14 Must Know Dev Tools Tricks', id: '09' },
  { name: 'Hold Shift to Check Multiple Checkboxes', id: '|0' },
  { name: 'Custom HTML5 Video Player', id: '11' },
  { name: 'Key Sequence Detection (KONAMI CODE)', id: '12' },
  { name: 'Slide In on Scroll', id: '13' },
  { name: 'Object and Arrays - Reference VS Copy', id: '14' },
  { name: 'LocalStorage and Event Delegation', id: '15' },
  { name: 'CSS Text Shadow Mouse Move Effect', id: '16' },
  { name: 'Sorting Band Names without articles', id: '17' },
  { name: 'Tally String Times with Reduce', id: '18' },
  { name: 'Unreal Webcam Fun', id: '19' },
  { name: 'Native Speech Recognition', id: '20' },
  { name: 'Geolocation based Speedometer and Compass', id: '21' },
  { name: 'Follow Along Links', id: '22' },
  { name: 'Speech Synthesis', id: '23' },
  { name: 'Sticky Nav', id: '24' },
  { name: 'Event Capture, Propagation, Bubbling and Once', id: '25' },
  { name: 'Stripe Follow Along Dropdown', id: '26' },
  { name: 'Click and Drag to Scroll', id: '27' },
  { name: 'Video Speed Controller UI', id: '28' },
  { name: 'Countdown Clock', id: '29' },
  { name: 'Whack A Mole Game', id: '30' },
  { name: 'That s All Folks!', id:' 31' }
];

export default clases;
